# -*- coding: utf-8 -*-
"""Реестр STAC-источников плагина STAC Hub.

Сгенерировано scripts/gen_sources.py из живых проверок 09.09.2026
(12 каталогов + 76 флагманских коллекций NASA CMR-STAC). Не редактируйте вручную —
правьте генератор и перезапускайте его.
"""

CHECK_DATE = "09.09.2026"

# (ключ, название) — категории данных (группировка дерева)
CATEGORIES = [
    ("imagery", "Космические снимки"),
    ("dem", "Рельеф и DEM"),
    ("vegetation", "Растительность и биомасса"),
    ("climate", "Климат и атмосфера"),
    ("hydro", "Гидрология и осадки"),
    ("ocean", "Океан"),
    ("cryo", "Криосфера и лёд"),
    ("events", "События и катастрофы"),
    ("sar", "Радиолокация (SAR)"),
    ("geodesy", "Геодезия и гравитация"),
    ("night", "Ночная подсветка"),
    ("multi", "Мультидисциплинарные платформы"),
]

# Словарь категория -> список человекочитаемых охватов (для группировки по охвату)
COVERAGE_GROUPS = [
    ("global", "Глобальные"),
    ("regional", "Региональные"),
    ("events", "События и сюжеты"),
]

SOURCES = [
    {
        'id': 'earthsearch',
        'name': 'EarthSearch (Element 84)',
        'operator': 'Element 84 / AWS Open Data',
        'url': 'https://earth-search.aws.element84.com/v1',
        'kind': 'api',
        'access': 'Анонимно',
        'license': 'открытые данные AWS (varies)',
        'coverage': 'Глобальный (NAIP — США)',
        'coverage_class': 'global',
        'auth': 'none',
        'auth_note': '',
        "categories": ['imagery', 'dem'],
        "collections": [
            {'id': 'sentinel-2-l2a', 'name': 'Sentinel-2 L2A (COG, поверхность)', 'category': 'imagery', 'note': 'Ежедневно; загрузка анонимна, S3+HTTPS'},
            {'id': 'landsat-c2-l2', 'name': 'Landsat Collection 2 L2', 'category': 'imagery', 'note': ''},
            {'id': 'naip', 'name': 'NAIP (США, 0.6–1 м)', 'category': 'imagery', 'note': 'Только территория США'},
            {'id': 'cop-dem-glo-30', 'name': 'Copernicus DEM 30 м', 'category': 'dem', 'note': 'Глобальная ЦМР'},
            {'id': 'cop-dem-glo-90', 'name': 'Copernicus DEM 90 м', 'category': 'dem', 'note': ''},
        ],
        'note': 'Анонимные COG; быстрый S3-хостинг; v1 API.',
    },
    {
        'id': 'landsatlook',
        'name': 'USGS LandsatLook',
        'operator': 'USGS',
        'url': 'https://landsatlook.usgs.gov/stac-server',
        'kind': 'api',
        'access': 'Анонимно',
        'license': 'public domain (USGS)',
        'coverage': 'Глобальный',
        'coverage_class': 'global',
        'auth': 'none',
        'auth_note': '',
        "categories": ['imagery', 'hydro', 'cryo'],
        "collections": [
            {'id': 'landsat-c2l2-sr', 'name': 'Landsat Collection 2 L2 (SR/ST)', 'category': 'imagery', 'note': 'С 1982; STAC USGS — партнёра NASA', 'sat': 'Landsat 4–9 (OLI/TIRS)', 'gsd': '30 м'},
            {'id': 'landsat-c2ard-sr', 'name': 'Landsat C2 ARD (тайлы анализа)', 'category': 'imagery', 'note': 'Analysis-Ready Data: тайлы для анализа', 'sat': 'Landsat 4–9', 'gsd': '30 м (тайл 5000×5000)'},
            {'id': 'landsat-c2l3-dswe', 'name': 'Landsat DSWE (открытая вода)', 'category': 'hydro', 'note': 'Динамические поверхностные воды', 'sat': 'Landsat 4–9', 'gsd': '30 м'},
            {'id': 'landsat-c2l3-fsca', 'name': 'Landsat FSCA (фракционный снежный покров)', 'category': 'cryo', 'note': 'Снежный покров', 'sat': 'Landsat 4–9', 'gsd': '30 м'},
        ],
        'note': 'Официальный STAC USGS: L2 поверхностное отражение, ARD, DSWE, fSCA; COG анонимно.',
    },
    {
        'id': 'cdse',
        'name': 'Copernicus Data Space Ecosystem',
        'operator': 'ESA / EU Space Programme',
        'url': 'https://stac.dataspace.copernicus.eu/v1',
        'kind': 'api',
        'access': 'Поиск анонимно; загрузка — бесплатный токен',
        'license': 'Copernicus (свободное использование)',
        'coverage': 'Глобальный',
        'coverage_class': 'global',
        'auth': 'bearer',
        'auth_note': 'Токен с account.dataspace.copernicus.eu (OAuth, бесплатно) — вставьте в поле Bearer.',
        "categories": ['imagery'],
        "collections": [
        ],
        'note': 'Sentinel-1/2/3/5P, CLMS; поиск анонимен, ассеты по Bearer-токену.',
    },
    {
        'id': 'terrascope',
        'name': 'Terrascope',
        'operator': 'VITO (Бельгия)',
        'url': 'https://stac.terrascope.be/',
        'kind': 'api',
        'access': 'Поиск анонимно; загрузка — бесплатный аккаунт',
        'license': 'varies (Copernicus/CLMS)',
        'coverage': 'Глобальный',
        'coverage_class': 'global',
        'auth': 'basic',
        'auth_note': 'Бесплатная регистрация terrascope.be; подойдёт Basic или Bearer.',
        "categories": ['imagery', 'multi'],
        "collections": [
        ],
        'note': 'Sentinel-1/2, PROBA-V, CLMS-продукты; зеркала Copernicus для быстрой загрузки.',
    },
    {
        'id': 'planetarycomputer',
        'name': 'Microsoft Planetary Computer',
        'operator': 'Microsoft',
        'url': 'https://planetarycomputer.microsoft.com/api/stac/v1',
        'kind': 'api',
        'access': 'Поиск анонимно; ассеты — SAS-подпись (плагин добавляет автоматически)',
        'license': 'varies (открытые данные)',
        'coverage': 'Глобальный',
        'coverage_class': 'global',
        'auth': 'header',
        'auth_note': 'Опционально: ключ API в заголовке Ocp-Apim-Subscription-Key (режим «Заголовок»). Без ключа тоже работает.',
        "categories": ['imagery', 'sar', 'multi', 'dem', 'climate'],
        "collections": [
            {'id': 'sentinel-2-l2a', 'name': 'Sentinel-2 L2A (поверхностное отражение)', 'category': 'imagery', 'note': 'Ежедневно; каналы B01–B12 по ассетам, есть visual; 2016+', 'sat': 'Sentinel-2 MSI', 'gsd': '10–60 м', 'level': 'L2', 'format': 'COG GeoTIFF', 'access': 'Анонимно (SAS)'},
            {'id': 'sentinel-1-grd', 'name': 'Sentinel-1 GRD (SAR)', 'category': 'sar', 'note': 'Каналы VV/VH (HH/HV) — по одному ассету на поляризацию; 2014+', 'sat': 'Sentinel-1 C-SAR', 'gsd': '~5×20 м', 'level': 'L1', 'format': 'COG GeoTIFF', 'access': 'Анонимно (SAS)'},
            {'id': 'sentinel-1-rtc', 'name': 'Sentinel-1 RTC (SAR, радиометр. коррекция)', 'category': 'sar', 'note': 'Гамма-ноль, готов к анализу; 2014+', 'sat': 'Sentinel-1 C-SAR', 'gsd': '30 м', 'level': 'L2', 'format': 'COG GeoTIFF', 'access': 'Анонимно (SAS)'},
            {'id': 'sentinel-5p-l2-netcdf', 'name': 'Sentinel-5P L2 (CO, NO2, CH4, O3)', 'category': 'climate', 'note': 'Газовые карты; NetCDF — в QGIS открывается как поднаборы', 'sat': 'Sentinel-5P TROPOMI', 'gsd': '~5.5×7 км', 'level': 'L2', 'format': 'NetCDF-4', 'access': 'Анонимно (SAS)'},
            {'id': 'sentinel-3-slstr-lst-l2-netcdf', 'name': 'Sentinel-3 SLSTR LST (температура поверхности)', 'category': 'climate', 'note': 'NetCDF; глобальные проходы ежедневно', 'sat': 'Sentinel-3 SLSTR', 'gsd': '1 км', 'level': 'L2', 'format': 'NetCDF-4', 'access': 'Анонимно (SAS)'},
            {'id': 'hls2-s30', 'name': 'HLS v2 Sentinel-2 (поверхн. отражение)', 'category': 'imagery', 'note': 'Гармонизирован с Landsat; 2015+', 'sat': 'Sentinel-2 MSI', 'gsd': '30 м', 'level': 'L2', 'format': 'COG GeoTIFF', 'access': 'Анонимно (SAS)'},
            {'id': '3dep-seamless', 'name': '3DEP Seamless DEM (США)', 'category': 'dem', 'note': 'Только США'},
            {'id': 'cop-dem-glo-30', 'name': 'Copernicus DEM 30 м', 'category': 'dem', 'note': ''},
            {'id': 'io-lulc-annual-v02', 'name': 'Impact Observatory LULC (годовые карты)', 'category': 'multi', 'note': ''},
            {'id': 'daymet-daily-na', 'name': 'Daymet Daily (Сев. Америка)', 'category': 'climate', 'note': ''},
        ],
        'note': '136 коллекций: Sentinel-1/2/3/5P, HLS, DEM, климат, землепользование; ассеты отдаются в Azure blob — плагин сам подписывает их SAS-токеном (без ключа API).',
    },
    {
        'id': 'cmrstac',
        'name': 'NASA CMR-STAC',
        'operator': 'NASA EOSDIS',
        'url': 'https://cmr.earthdata.nasa.gov/stac/',
        'kind': 'api',
        'access': 'Поиск анонимно; загрузка — Earthdata Login (бесплатно)',
        'license': 'NASA open (varies по DAAC)',
        'coverage': 'Глобальный',
        'coverage_class': 'global',
        'auth': 'basic',
        'auth_note': 'Бесплатный Earthdata Login (urs.earthdata.nasa.gov). Basic (логин/пароль) или Bearer-токен LP DAAC.',
        "categories": [],
        "collections": [
            {'id': 'HLSS30_2.0', 'name': 'HLS Sentinel-2 L2A (поверхностное отражение)', 'category': 'imagery', 'note': 'Гармонизирован с Landsat; высокая частота съёмки; 2015+', 'sat': 'Sentinel-2 MSI', 'gsd': '30 м', 'level': 'L2', 'format': 'COG GeoTIFF', 'access': 'Earthdata Login'},
            {'id': 'HLSL30_2.0', 'name': 'HLS Landsat 8/9 L2', 'category': 'imagery', 'note': 'Совместный ряд HLS; 2013+', 'sat': 'Landsat 8/9 OLI/OLI-2', 'gsd': '30 м', 'level': 'L2', 'format': 'COG GeoTIFF', 'access': 'Earthdata Login'},
            {'id': 'EMITL2ARFL_001', 'name': 'EMIT поверхностное отражение', 'category': 'imagery', 'note': 'Изображающая спектрометрия; 2022+', 'sat': 'ISS EMIT спектрометр', 'gsd': '60 м', 'level': 'L2', 'format': 'NetCDF-4', 'access': 'Earthdata Login'},
            {'id': 'EMITL2BMIN_001', 'name': 'EMIT минералогия', 'category': 'climate', 'note': 'Карта поверхностных минералов; пыльные источники', 'sat': 'ISS EMIT', 'gsd': '60 м', 'level': 'L2', 'format': 'NetCDF-4', 'access': 'Earthdata Login'},
            {'id': 'EMITL2BCH4ENH_002', 'name': 'EMIT метановые пламёжа', 'category': 'climate', 'note': 'Детекция утечек метана и CO2; 2022+', 'sat': 'ISS EMIT', 'gsd': '60 м', 'level': 'L2', 'format': 'NetCDF-4', 'access': 'Earthdata Login'},
            {'id': 'GEDI02_A_002', 'name': 'GEDI структура леса', 'category': 'vegetation', 'note': 'Высоты полога и профили; 2019+', 'sat': 'ISS GEDI лидар', 'gsd': '25 м (след)', 'level': 'L2', 'format': 'HDF-5', 'access': 'Earthdata Login'},
            {'id': 'GEDI_L4A_AGB_Density_V2_1_2056_2.1', 'name': 'GEDI биомасса (AGB)', 'category': 'vegetation', 'note': 'Плотность надземной биомассы; распределён ORNL DAAC', 'sat': 'ISS GEDI', 'gsd': '25 м (след)', 'level': 'L4', 'format': 'HDF-5', 'access': 'Earthdata Login'},
            {'id': 'ECO_L2T_LSTE_002', 'name': 'ECOSTRESS температура поверхности', 'category': 'climate', 'note': 'Суточный цикл LST; 2018+', 'sat': 'ISS ECOSTRESS', 'gsd': '70 м', 'level': 'L2', 'format': 'COG GeoTIFF', 'access': 'Earthdata Login'},
            {'id': 'ECO_L4T_ESI_002', 'name': 'ECOSTRESS индекс стресса влаги', 'category': 'climate', 'note': 'Засухи, испарение; 2018+', 'sat': 'ISS ECOSTRESS', 'gsd': '70 м', 'level': 'L4', 'format': 'COG GeoTIFF', 'access': 'Earthdata Login'},
            {'id': 'AST_L1T_004', 'name': 'ASTER L1T', 'category': 'imagery', 'note': 'Радиометрически/геометрически скорректирован; 2000+', 'sat': 'Terra ASTER', 'gsd': '15/30/90 м', 'level': 'L1', 'format': 'GeoTIFF', 'access': 'Earthdata Login'},
            {'id': 'ASTGTM_003', 'name': 'ASTER GDEM v3 (ЦМР)', 'category': 'dem', 'note': 'Глобальная ЦМР; съёмки 2000–2011', 'sat': 'Terra ASTER', 'gsd': '30 м', 'level': 'DEM', 'format': 'GeoTIFF', 'access': 'Earthdata Login'},
            {'id': 'SRTMGL1_003', 'name': 'SRTM 1″ (ЦМР)', 'category': 'dem', 'note': '56° ю.ш.–60° с.ш.; февраль 2000', 'sat': 'Space Shuttle SRTM', 'gsd': '30 м', 'level': 'DEM', 'format': 'GeoTIFF', 'access': 'Earthdata Login'},
            {'id': 'NASADEM_HGT_001', 'name': 'NASADEM (ЦМР)', 'category': 'dem', 'note': 'Улучшенный ре-процессинг SRTM', 'sat': 'SRTM (переработка)', 'gsd': '30 м', 'level': 'DEM', 'format': 'GeoTIFF', 'access': 'Earthdata Login'},
            {'id': 'MCD43A4_061', 'name': 'MODIS NBAR (BRDF-отражение)', 'category': 'imagery', 'note': 'Ежедневно; 2000+', 'sat': 'Terra + Aqua', 'gsd': '500 м', 'level': 'L3', 'format': 'HDF-4', 'access': 'Earthdata Login'},
            {'id': 'MOD13Q1_061', 'name': 'MODIS NDVI/EVI (Terra)', 'category': 'vegetation', 'note': '16 дней; 2000+', 'sat': 'Terra', 'gsd': '250 м', 'level': 'L3', 'format': 'HDF-4', 'access': 'Earthdata Login'},
            {'id': 'MYD13Q1_061', 'name': 'MODIS NDVI/EVI (Aqua)', 'category': 'vegetation', 'note': '16 дней; 2002+', 'sat': 'Aqua', 'gsd': '250 м', 'level': 'L3', 'format': 'HDF-4', 'access': 'Earthdata Login'},
            {'id': 'MCD64A1_061', 'name': 'MODIS выгоревшие площади', 'category': 'vegetation', 'note': 'Ежемесячно; 2000+', 'sat': 'Terra + Aqua', 'gsd': '500 м', 'level': 'L3', 'format': 'HDF-4', 'access': 'Earthdata Login'},
            {'id': 'MOD11A2_061', 'name': 'MODIS LST (температура поверхности)', 'category': 'imagery', 'note': '8 дней; 2000+', 'sat': 'Terra', 'gsd': '1 км', 'level': 'L3', 'format': 'HDF-4', 'access': 'Earthdata Login'},
            {'id': 'MOD17A2HGF_061', 'name': 'MODIS GPP (продуктивность)', 'category': 'vegetation', 'note': 'Валовая первичная продуктивность, 8 дней; 2000+', 'sat': 'Terra', 'gsd': '500 м', 'level': 'L4', 'format': 'HDF-4', 'access': 'Earthdata Login'},
            {'id': 'MOD17A3HGF_061', 'name': 'MODIS NPP (годовая)', 'category': 'vegetation', 'note': 'Чистая первичная продуктивность; 2001+', 'sat': 'Terra', 'gsd': '500 м', 'level': 'L4', 'format': 'HDF-4', 'access': 'Earthdata Login'},
            {'id': 'VNP13A1_002', 'name': 'VIIRS NDVI/EVI', 'category': 'vegetation', 'note': 'Продолжение MODIS-ряда; 2012+', 'sat': 'Suomi-NPP VIIRS', 'gsd': '500 м', 'level': 'L3', 'format': 'HDF-4', 'access': 'Earthdata Login'},
            {'id': 'MCD19A2_061', 'name': 'MODIS MAIAC аэрозоли (AOD)', 'category': 'climate', 'note': 'Оптическая толща аэрозоля; 2000+', 'sat': 'Terra + Aqua', 'gsd': '1 км', 'level': 'L2G', 'format': 'HDF-4', 'access': 'Earthdata Login'},
            {'id': 'OPERA_L2_RTC-S1_V1_1', 'name': 'OPERA RTC (радиометрическая коррекция)', 'category': 'sar', 'note': 'Готовые карты обратного рассеяния; 2016+', 'sat': 'Sentinel-1 C-band', 'gsd': '30 м', 'level': 'L2', 'format': 'COG GeoTIFF', 'access': 'Earthdata Login'},
            {'id': 'OPERA_L3_DISP-S1_V1_1', 'name': 'OPERA деформации поверхности', 'category': 'sar', 'note': 'Смещения поверхности (просадки/подъёмы); 2016+', 'sat': 'Sentinel-1 (InSAR)', 'gsd': '30 м', 'level': 'L3', 'format': 'COG GeoTIFF', 'access': 'Earthdata Login'},
            {'id': 'OPERA_L4_TROPO-ZENITH_V1_1', 'name': 'OPERA тропосферная коррекция', 'category': 'climate', 'note': 'Коррекция InSAR за тропосферу', 'sat': 'ERA5 + орбиты Sentinel-1', 'gsd': 'грид ~30 м', 'level': 'L4', 'format': 'COG GeoTIFF', 'access': 'Earthdata Login'},
            {'id': 'SENTINEL-1A_SLC_1', 'name': 'Sentinel-1A SLC', 'category': 'sar', 'note': 'Исходные сложные изображения; 2014+', 'sat': 'Sentinel-1A', 'gsd': '~5×20 м', 'level': 'L1', 'format': 'SAFE (zip)', 'access': 'Earthdata Login'},
            {'id': 'MUR-JPL-L4-GLOB-v4.1_4.1', 'name': 'MUR SST (температура поверхности)', 'category': 'ocean', 'note': 'Ежедневно; с 2002', 'sat': 'Мультидатчиковый GHRSST', 'gsd': '1 км', 'level': 'L4', 'format': 'NetCDF-4', 'access': 'Earthdata Login'},
            {'id': 'SWOT_L2_LR_SSH_2.0_2.0', 'name': 'SWOT уровень поверхности океана', 'category': 'ocean', 'note': 'Первая карта топографии океана широкоугольным лидаром-альтиметром; 2022+', 'sat': 'SWOT KaRIn + альтиметр', 'gsd': 'свотч ~2 км', 'level': 'L2', 'format': 'NetCDF-4', 'access': 'Earthdata Login'},
            {'id': 'JASON_CS_S6A_L2_ALT_HR_STD_OST_STC_F_F', 'name': 'Sentinel-6A MF (уровень моря)', 'category': 'ocean', 'note': 'Продолжение топографического ряда уровня моря; 2020+', 'sat': 'Sentinel-6 Poseidon-4', 'gsd': 'трековый', 'level': 'L2', 'format': 'NetCDF-4', 'access': 'Earthdata Login'},
            {'id': 'TELLUS_GRAC-GRFO_MASCON_CRI_GRID_RL06.3_V4_R', 'name': 'GRACE/GRACE-FO масконы (запасы воды)', 'category': 'geodesy', 'note': 'Аномалии массы воды (засухи/паводки); 2002+', 'sat': 'GRACE / GRACE-FO', 'gsd': '3° (маскон)', 'level': 'L4', 'format': 'NetCDF-4', 'access': 'Earthdata Login'},
            {'id': 'CYGNSS_L1_V3.2_3.2', 'name': 'CYGNSS скорость ветра', 'category': 'ocean', 'note': 'Ветер над океаном (в т.ч. в ураганах); 2018+', 'sat': 'CYGNSS GNSS-рефлектометрия', 'gsd': '~км (свотч)', 'level': 'L1', 'format': 'NetCDF-4', 'access': 'Earthdata Login'},
            {'id': 'OSCAR_L4_OC_NRT_V2.0_2.0', 'name': 'OSCAR поверхностные течения', 'category': 'ocean', 'note': 'NRT-течения; в STAC с 2021 (ряд OSCAR ведётся с 1992)', 'sat': 'Мультидатчиковый', 'gsd': '0.5°', 'level': 'L4', 'format': 'NetCDF-4', 'access': 'Earthdata Login'},
            {'id': 'ECCO_L4_HEAT_FLUX_05DEG_DAILY_V4R4_V4r4', 'name': 'ECCO океанский реанализ', 'category': 'ocean', 'note': 'Поверхностные тепловые потоки; 1992–2018', 'sat': 'Модель MITgcm + наблюдения', 'gsd': '0.5°', 'level': 'L4', 'format': 'NetCDF-4', 'access': 'Earthdata Login'},
            {'id': 'GPM_3IMERGHH_07', 'name': 'GPM IMERG осадки (30 мин)', 'category': 'hydro', 'note': 'Глобальные осадки; ряд с 1998 (TRMM-эра)', 'sat': 'GPM GMI/DPR + микроволн. констелляция', 'gsd': '0.1°', 'level': 'L3', 'format': 'NetCDF-4', 'access': 'Earthdata Login'},
            {'id': 'TRMM_3B42_Daily_7', 'name': 'TRMM 3B42 суточные осадки', 'category': 'hydro', 'note': 'Исторический ряд 1998–2019', 'sat': 'TRMM', 'gsd': '0.25°', 'level': 'L3', 'format': 'NetCDF-4', 'access': 'Earthdata Login'},
            {'id': 'M2T1NXSLV_5.12.4', 'name': 'MERRA-2 реанализ (часовой)', 'category': 'climate', 'note': 'Метеорологические поля; с 1980', 'sat': 'Модель GMAO', 'gsd': '0.5°×0.625°', 'level': 'Реанализ', 'format': 'NetCDF-4', 'access': 'Earthdata Login'},
            {'id': 'M2TMNXSLV_5.12.4', 'name': 'MERRA-2 реанализ (месячный)', 'category': 'climate', 'note': 'Месячные средние; с 1980', 'sat': 'Модель GMAO', 'gsd': '0.5°×0.625°', 'level': 'Реанализ', 'format': 'NetCDF-4', 'access': 'Earthdata Login'},
            {'id': 'AIRS3STD_7.0', 'name': 'AIRS L3 (профили T/H2O)', 'category': 'climate', 'note': 'Суточные; с 2002', 'sat': 'Aqua AIRS', 'gsd': '1°', 'level': 'L3', 'format': 'NetCDF-4', 'access': 'Earthdata Login'},
            {'id': 'OMNO2d_003', 'name': 'OMI NO2 (месячный)', 'category': 'climate', 'note': 'Тропосферный столб NO2; 2004+', 'sat': 'Aura OMI', 'gsd': '0.25°', 'level': 'L3', 'format': 'HDF-EOS5', 'access': 'Earthdata Login'},
            {'id': 'OMSO2e_004', 'name': 'OMI SO2 (дневной L3)', 'category': 'climate', 'note': 'Диоксид серы; 2004+', 'sat': 'Aura OMI', 'gsd': '0.25°', 'level': 'L3', 'format': 'HDF-EOS5', 'access': 'Earthdata Login'},
            {'id': 'NLDAS_FORA0125_H_2.0', 'name': 'NLDAS-2 форсинг (часовой)', 'category': 'hydro', 'note': 'Северная Америка; с 1979', 'sat': 'Реанализ NCEP', 'gsd': '0.125°', 'level': 'L4', 'format': 'NetCDF-4/GRIB', 'access': 'Earthdata Login'},
            {'id': 'GLDAS_NOAH025_3H_2.1', 'name': 'GLDAS Noah (3 ч)', 'category': 'hydro', 'note': 'Глобальная модель суши; с 2000', 'sat': 'Модель Noah', 'gsd': '0.25°', 'level': 'L4', 'format': 'NetCDF-4', 'access': 'Earthdata Login'},
            {'id': 'OCO2_L2_Lite_FP_11.2r', 'name': 'OCO-2 XCO2', 'category': 'climate', 'note': 'Столбовая концентрация CO2; 2014+', 'sat': 'OCO-2', 'gsd': 'трековый', 'level': 'L2', 'format': 'NetCDF-4', 'access': 'Earthdata Login'},
            {'id': 'OCO3_L2_Lite_SIF_11r', 'name': 'OCO-3 SIF (флуоресценция)', 'category': 'climate', 'note': 'Солнечно-индуцированная флуоресценция; 2019+', 'sat': 'ISS OCO-3', 'gsd': '~2–3 км', 'level': 'L2', 'format': 'NetCDF-4', 'access': 'Earthdata Login'},
            {'id': 'OCO2_L2_Lite_SIF_11.2r', 'name': 'OCO-2 SIF', 'category': 'climate', 'note': 'С 2014', 'sat': 'OCO-2', 'gsd': '~1.3×2.2 км', 'level': 'L2', 'format': 'NetCDF-4', 'access': 'Earthdata Login'},
            {'id': 'ATL06_007', 'name': 'ICESat-2 высоты ледников', 'category': 'cryo', 'note': 'Сушёный лёд; 2018+', 'sat': 'ATLAS лидар', 'gsd': 'точки ~17 м', 'level': 'L3A', 'format': 'HDF-5', 'access': 'Earthdata Login'},
            {'id': 'ATL08_007', 'name': 'ICESat-2 суша и растительность', 'category': 'cryo', 'note': 'Высоты суши и полога; 2018+', 'sat': 'ATLAS лидар', 'gsd': '~100 м', 'level': 'L3A', 'format': 'HDF-5', 'access': 'Earthdata Login'},
            {'id': 'ATL10_007', 'name': 'ICESat-2 морской лёд', 'category': 'cryo', 'note': 'Свободный борт морского льда; 2018+', 'sat': 'ATLAS лидар', 'gsd': 'свотч', 'level': 'L3A', 'format': 'HDF-5', 'access': 'Earthdata Login'},
            {'id': 'ATL15_005', 'name': 'ICESat-2 гриды высот льда', 'category': 'cryo', 'note': 'Антарктика и Арктика; 2019+', 'sat': 'ATLAS лидар', 'gsd': '1–40 км', 'level': 'L3B', 'format': 'NetCDF-4', 'access': 'Earthdata Login'},
            {'id': 'MOD10A1_61', 'name': 'MODIS снежный покров', 'category': 'cryo', 'note': 'Ежедневно; 2000+', 'sat': 'Terra', 'gsd': '500 м', 'level': 'L3', 'format': 'HDF-4', 'access': 'Earthdata Login'},
            {'id': 'MYD10A1_61', 'name': 'MODIS снежный покров (Aqua)', 'category': 'cryo', 'note': '2002+', 'sat': 'Aqua', 'gsd': '500 м', 'level': 'L3', 'format': 'HDF-4', 'access': 'Earthdata Login'},
            {'id': 'SPL3SMP_E_006', 'name': 'SMAP L3 почвенная влага', 'category': 'cryo', 'note': 'Enhanced-грид; 2015+', 'sat': 'SMAP L-диапазон', 'gsd': '9 км', 'level': 'L3', 'format': 'HDF-5', 'access': 'Earthdata Login'},
            {'id': 'SPL4SMLM_008', 'name': 'SMAP L4 влага корневой зоны', 'category': 'hydro', 'note': 'С 2015', 'sat': 'SMAP + модель', 'gsd': '9 км', 'level': 'L4', 'format': 'HDF-5', 'access': 'Earthdata Login'},
            {'id': 'SPL4CMDL_008', 'name': 'SMAP L4 углерод (NEE)', 'category': 'vegetation', 'note': 'Обмен CO2 между сушей и атмосферой; 2015+', 'sat': 'SMAP + модель', 'gsd': '9 км', 'level': 'L4', 'format': 'HDF-5', 'access': 'Earthdata Login'},
            {'id': 'VNP46A1_2', 'name': 'Black Marble L1 (DNB)', 'category': 'night', 'note': 'Дневно-ночная полоса, грид; 2012+', 'sat': 'Suomi-NPP VIIRS', 'gsd': '15″ (~500 м)', 'level': 'L1', 'format': 'HDF-5', 'access': 'Earthdata Login'},
            {'id': 'VNP46A2_2', 'name': 'Black Marble (ежедневные огни)', 'category': 'night', 'note': 'Безлунная BRDF-коррекция; 2012+', 'sat': 'Suomi-NPP VIIRS', 'gsd': '15″ (~500 м)', 'level': 'L2', 'format': 'HDF-5', 'access': 'Earthdata Login'},
            {'id': 'VNP46A3_2', 'name': 'Black Marble (месячный)', 'category': 'night', 'note': '2012+', 'sat': 'Suomi-NPP VIIRS', 'gsd': '15″ (~500 м)', 'level': 'L3', 'format': 'HDF-5', 'access': 'Earthdata Login'},
            {'id': 'VNP46A4_2', 'name': 'Black Marble (годовой)', 'category': 'night', 'note': '2012+', 'sat': 'Suomi-NPP VIIRS', 'gsd': '15″ (~500 м)', 'level': 'L3', 'format': 'HDF-5', 'access': 'Earthdata Login'},
            {'id': 'MOD021KM_6.1', 'name': 'MODIS L1B раданс (1 км)', 'category': 'imagery', 'note': 'Сырые калиброванные данные; 2000+', 'sat': 'Terra', 'gsd': '1 км', 'level': 'L1B', 'format': 'HDF-4', 'access': 'Earthdata Login'},
            {'id': 'MYD021KM_6.1', 'name': 'MODIS L1B раданс (Aqua)', 'category': 'imagery', 'note': '2002+', 'sat': 'Aqua', 'gsd': '1 км', 'level': 'L1B', 'format': 'HDF-4', 'access': 'Earthdata Login'},
            {'id': 'MODISA_L3m_CHL_2022.0', 'name': 'Хлорофилл-a (MODIS-Aqua)', 'category': 'ocean', 'note': 'Глобальный океанский цвет; 2002+', 'sat': 'MODIS-Aqua', 'gsd': '4 км', 'level': 'L3', 'format': 'NetCDF-4', 'access': 'Анонимно'},
            {'id': 'VIIRSN_L3m_CHL_2022.0', 'name': 'Хлорофилл-a (VIIRS NPP)', 'category': 'ocean', 'note': '2012+', 'sat': 'Suomi-NPP VIIRS', 'gsd': '4 км', 'level': 'L3', 'format': 'NetCDF-4', 'access': 'Анонимно'},
            {'id': 'VIIRSJ1_L3m_CHL_2022.0', 'name': 'Хлорофилл-a (NOAA-20)', 'category': 'ocean', 'note': '2017+', 'sat': 'NOAA-20 VIIRS', 'gsd': '4 км', 'level': 'L3', 'format': 'NetCDF-4', 'access': 'Анонимно'},
            {'id': 'SeaWiFS_L3m_CHL_2022.0', 'name': 'Хлорофилл-a (SeaWiFS)', 'category': 'ocean', 'note': 'Исторический ряд 1997–2010', 'sat': 'OrbView-2 SeaWiFS', 'gsd': '9 км', 'level': 'L3', 'format': 'NetCDF-4', 'access': 'Анонимно'},
            {'id': 'MODISA_L2_OC_2022.0', 'name': 'L2 океанский цвет (Aqua)', 'category': 'ocean', 'note': 'Свотчи уровня L2', 'sat': 'MODIS-Aqua', 'gsd': '1 км', 'level': 'L2', 'format': 'NetCDF-4', 'access': 'Анонимно'},
            {'id': 'CERES_EBAF_Edition4.2.1', 'name': 'CERES EBAF (баланс излучения)', 'category': 'climate', 'note': 'Потоки излучения TOA и поверхности; ежемесячно; 2000+', 'sat': 'Terra/Aqua/Suomi-NPP', 'gsd': '1°', 'level': 'L3', 'format': 'NetCDF-4', 'access': 'Earthdata Login'},
            {'id': 'CAL_LID_L2_01kmCLay-Standard-V5-00_V5-00', 'name': 'CALIPSO слои облаков и аэрозолей', 'category': 'climate', 'note': 'Вертикальные профили 2006–2023', 'sat': 'CALIPSO лидар', 'gsd': '1 км (верт. 30–60 м)', 'level': 'L2', 'format': 'HDF-4', 'access': 'Earthdata Login'},
            {'id': 'Daymet_Daily_V4R1_2129_4.1', 'name': 'Daymet суточная погода', 'category': 'climate', 'note': 'Северная Америка; 1950–2025', 'sat': 'Интерполяция метеостанций', 'gsd': '1 км', 'level': 'L4', 'format': 'NetCDF-4', 'access': 'Earthdata Login (THREDDS — анонимно)'},
            {'id': 'Daymet_Monthly_V4R1_2131_4.1', 'name': 'Daymet месячные климатологии', 'category': 'climate', 'note': '1950–2024', 'sat': 'Интерполяция метеостанций', 'gsd': '1 км', 'level': 'L4', 'format': 'NetCDF-4', 'access': 'Earthdata Login (THREDDS — анонимно)'},
            {'id': 'isslis_v3_fin_3', 'name': 'ISS LIS молнии (QC)', 'category': 'climate', 'note': 'Контролированные вспышки молний; 2017–2023', 'sat': 'ISS LIS', 'gsd': 'трековый', 'level': 'L2', 'format': 'NetCDF-4', 'access': 'Earthdata Login'},
            {'id': 'GNSS_ERP_prod_1', 'name': 'GNSS параметры вращения Земли', 'category': 'geodesy', 'note': 'С 1992', 'sat': 'Сеть IGS', 'gsd': '—', 'level': 'Решения', 'format': 'ASCII/XML', 'access': 'Earthdata Login'},
            {'id': 'LANDSAT_SURFACE_REFLECTANCE_L4-5_TM', 'name': 'Landsat 4–5 TM поверхностное отражение', 'category': 'imagery', 'note': 'Исторический архив 1982–2013', 'sat': 'Landsat-5 TM', 'gsd': '30 м', 'level': 'L2', 'format': 'GeoTIFF', 'access': 'Earthdata Login'},
        ],
        'note': 'Федеративный каталог EOSDIS: 61 провайдер. Поиск идёт по провайдерам CMR; 76 флагманских наборов встроено.',
        "key_providers": ['LPCLOUD', 'LAADS', 'POCLOUD', 'GES_DISC', 'NSIDC_CPRD', 'OB_CLOUD', 'ASF', 'ORNL_CLOUD', 'LARC_CLOUD'],
    },
    {
        'id': 'vantor',
        'name': 'Vantor Open Data Program',
        'operator': 'Vantor (бывш. Maxar Intelligence)',
        'url': 'https://vantor-opendata.s3.amazonaws.com/events/catalog.json',
        'kind': 'static',
        'access': 'Анонимно',
        'license': 'CC BY-NC 4.0',
        'coverage': 'Зоны катастроф 2026',
        'coverage_class': 'events',
        'auth': 'none',
        'auth_note': '',
        "categories": ['events'],
        "collections": [
        ],
        'note': 'Сверхвысокое разрешение (0.3–0.6 м) WorldView/Legion по свежим катастрофам; COG + JPG, анонимный S3.',
    },
    {
        'id': 'maxar_legacy',
        'name': 'Maxar Open Data (архив)',
        'operator': 'Maxar Technologies',
        'url': 'https://maxar-opendata.s3.amazonaws.com/events/catalog.json',
        'kind': 'static',
        'access': 'Анонимно',
        'license': 'CC BY-NC 4.0',
        'coverage': 'Зоны катастроф 2023–2025',
        'coverage_class': 'events',
        'auth': 'none',
        'auth_note': '',
        "categories": ['events'],
        "collections": [
        ],
        'note': '55+ событий 2023–2025; тот же формат, что и Vantor; COG анонимно.',
    },
    {
        'id': 'umbra',
        'name': 'Umbra Open Data',
        'operator': 'Umbra Space',
        'url': 'https://umbra-open-data-catalog.s3.amazonaws.com/stac/catalog.json',
        'kind': 'static',
        'access': 'Анонимно',
        'license': 'CC BY-NC-SA 4.0 (varies)',
        'coverage': 'Точечные сюжеты по миру',
        'coverage_class': 'events',
        'auth': 'none',
        'auth_note': '',
        "categories": ['sar'],
        "collections": [
        ],
        'note': 'X-band SAR до 25 см/пикс; открытые сюжеты (GEC/GICTD).',
    },
    {
        'id': 'deafrica',
        'name': 'Digital Earth Africa',
        'operator': 'DE Africa / Geoscience Australia',
        'url': 'https://explorer.digitalearth.africa/stac',
        'kind': 'api',
        'access': 'Анонимно',
        'license': 'CC BY 4.0 (varies)',
        'coverage': 'Африка',
        'coverage_class': 'regional',
        'auth': 'none',
        'auth_note': '',
        "categories": ['multi'],
        "collections": [
        ],
        'note': '106 продуктов: Sentinel-2 годовые мозаики, WATERB, CHIRPS и др.',
    },
    {
        'id': 'dea',
        'name': 'Digital Earth Australia',
        'operator': 'Geoscience Australia',
        'url': 'https://explorer.dea.ga.gov.au/stac',
        'kind': 'api',
        'access': 'Анонимно',
        'license': 'CC BY 4.0 (varies)',
        'coverage': 'Австралия',
        'coverage_class': 'regional',
        'auth': 'none',
        'auth_note': '',
        "categories": ['multi'],
        "collections": [
        ],
        'note': 'Geomedian, WOFS (вода), Fractional Cover, NIDEM и др.',
    },
    {
        'id': 'bdc',
        'name': 'Brazil Data Cube',
        'operator': 'INPE (Бразилия)',
        'url': 'https://data.inpe.br/bdc/stac/v1/',
        'kind': 'api',
        'access': 'Анонимно',
        'license': 'open (INPE)',
        'coverage': 'Юж. Америка (Бразилия)',
        'coverage_class': 'regional',
        'auth': 'none',
        'auth_note': '',
        "categories": ['multi'],
        "collections": [
        ],
        'note': 'Кубы данных Sentinel-2/Landsat (S2-16D и др.), классификации CBERS.',
    },
]

def category_label(key):
    for k, label in CATEGORIES:
        if k == key:
            return label
    return key

def get_source(source_id):
    for s in SOURCES:
        if s["id"] == source_id:
            return s
    return None
